apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-broadcaster-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-broadcaster
  template:
    metadata:
      labels:
        app: hello-broadcaster
    spec:
      containers:
      - name: hello-broadcaster
        image: hello_broadcaster:latest
        imagePullPolicy: IfNotPresent
