apiVersion: v1
kind: Service
metadata:
  name: web-interface
spec:
  type: NodePort
  selector:
    app: web-interface
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007
